# Generated by Django 4.2.7 on 2023-11-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_number",
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
