# Generated by Django 4.2.7 on 2023-11-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_alter_phonenumber_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
