# Generated by Django 4.2.7 on 2023-11-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_contact_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_number",
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
