# Generated by Django 4.2.7 on 2023-11-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_alter_phonenumber_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetDateInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interval", models.IntegerField(default=7, max_length=3)),
            ],
        ),
    ]
