# Generated by Django 4.2.7 on 2023-11-14 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0007_alter_targetdateinterval_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetdateinterval",
            name="owner",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
