# Generated by Django 4.2.7 on 2023-11-14 20:16

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0009_delete_targetdateinterval"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="dob_dayofyear_internal",
            field=models.PositiveSmallIntegerField(
                default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="dob",
            field=birthday.fields.BirthdayField(blank=True, null=True),
        ),
    ]
