# Generated by Django 4.2.7 on 2023-11-15 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0011_dobinterval"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DOBInterval",
        ),
    ]
