# Generated by Django 4.2.7 on 2023-11-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_uploadedfile_is_deleted_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
