# Generated by Django 4.2.7 on 2023-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_delete_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10),
        ),
    ]
