# Generated by Django 4.2.7 on 2023-11-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='tag_of_username',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
    ]
