# Generated by Django 4.2.7 on 2023-11-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(),
        ),
    ]
